server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  error_page 404 /404.html;
  location / {
    try_files $uri $uri/index.html =404;
  }
  location ~* \.(webp|png|jpg|jpeg|svg|css|js|woff2)$ {
    expires 7d;
    add_header Cache-Control "public";
  }
  # Nada interno debe servirse jamás
  location ~* \.(pdf|docx|pptx|zip|ai|md)$ { return 404; }
}
